version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: RMQ-randonINT
    ports:
      - "5672:5672"
      - "15672:15672"
    # volumes:
    #   - ./rabbitmq:/var/lib/rabbitmq                       *для локального хранения при перезапуске контейнера*
    #   - ./rabbitmq/logs/:/var/log/rabbitmq/
      
  clickhouse:
    image: yandex/clickhouse-server:21.7     # image: clickhouse/clickhouse-server:latest
    container_name: CH-randonINT
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=secret
      - CLICKHOUSE_DATABASE=storageRANDOM
    volumes:
      - ./data:/var/lib/clickhouse2
      - ./migrations/init_rand_table.sql:/docker-entrypoint-initdb.d/init_rand_table.sql
    ports:
      - "8123:8123"
      - "19000:9000"
    restart: always
